### ISSUE TITLE
[8장] '단방향'매핑전략

### ISSUE THREAD

**Issue by kwanguuuu** [yegachefu/clean-architecture-example#2]
> p.103 이 전략에서는 모든 계층의 모델들이 같은 인터페이스를 구현한다.
> **이 인터페이스는 관련 있는 특성에 대한 getter 메서드를 제공해서 도메인 모델의 상태를 캡슐화 한다.**
> ...
> 바깥 계층에서 상태 인터페이스를 이용할지, 전용 모델로 매핑해야 할지 결정할 수 있다.

다이어그램을 보면 단방향 매핑의 모델은 모든 계층에서 '상태' 인터페이스를 구현한 도메인/어댑터 모델을 이용해 계층마다 단방향으로 매핑하면 된다는데, 
단반향 매핑을 호출하는게 getter란 말인가요.??
제가 이해를 못하고 있는것 같은 부분 ㅜ

**Comment by mychum1** [comment]
getter 메소드는 인터페이스로 숨겨진 필드를 접근해주도록 열어줘서 캡슐화를 해주는 도구??라서 '단방향' 매핑을 했을 때 얻을 수 있는 장점인 것 같고, 
모든 모델이 '상태' 인터페이스를 구현했으니 '양방향'처럼 바깥으로 전달할 때 별도로 매핑할 필요가 없어서 단방향 호출이 되는 것 같아요..!

**Comment by leeyohan93** [comment]
책에서 단반향 매핑이란 다음을 의미하는 것 같습니다.
상태 인터페이스(getter를 가진 인터페이스)를 각 모델들이 구현하고 있기 때문에 
각 계층에서는 상태 인터페이스를 해당 계층에서 이용할 수 있도록 다른 무언가로 매핑하거나, 그대로 사용할 수 있고 이 부분이 아래와 같이 단방향으로 이루어지기 때문에 `단방향 매핑`이라고 지칭하고 있습니다
- 상태 인터페이스 -> 도메인 모델
- 상태 인터페이스 -> 웹 모델
- 상태 인터페이스 -> 영속성 모델
