### ISSUE TITLE
[8장] 질문 3가지 ㅜ

### ISSUE THREAD

**Issue by mychum1** [yegachefu/clean-architecture-example#5]
1. 양방향 매핑의 단점 중에 
> 101p. 특히 매핑 프레임워크가 내부 동작 방식을 제네릭 코드와 리플렉션 뒤로 숨길 경우 매핑 로직을 디버깅하는 것은 꽤나 고통스럽기 때문이다.

라고 하는데, 테슬라나 포르쉐에서도 매퍼 어노테이션을 통해 일치하는 필드들을 자동으로 매핑해주는 부분이 있는데 이런 경우를 얘기하는 것일까요?

2. 똑같이, 양방향 매핑의 단점 
> 101p. 도메인 모델이 계층 경계를 넘어서 통신하는 데 사용되고 있다는 것이다.

각 어댑터와 컨트롤러가 도메인 모델을 자신이 사용하는 모델로 매핑할텐데 통신에 이용한다는 것은 무엇일까요? 추측에는 쨋든 도메인 모델을 반환해야 받는 쪽에서 그걸 가지고 매핑을 하는데 필드가 변경되면 받는 쪽 매퍼도 영향을 받아서 수정을 해야하니까? 그게 단점이고, 전달한다는걸 통신한다고 표현한다는건지..

3. 완전 매핑 전략의 단점 
> 103p. 애플리케이션 계층과 영속성 계층 사이에는 매핑 오버헤드 때문에 사용하지 않는 것이 좋다. 

매핑할 필드가 많기 때문에 매핑 오버헤드 때문이라고 한 것인지..?

**Comment by leeyohan93** [comment]
1. 네 맞습니다. 매퍼 어노테이션을 통해 일치하는 필드를 자동으로 매핑해주거나, 맵스트럭트 같은 경우를 이야기하는 것입니당!

2. 추측하신게 맞습니다. 저도 도메인 모델을 통신에 이용한다는 것은 각 포트의 인자 또는 반환값으로 도메인 모델을 사용하는 부분을 이야기하고 있는 것으로 이해했어요. 바깥쪽 요구에 따른 변경의 취약은 10장 `도메인 엔티티를 입출력 모델로 사용하기`를 보면 예시가 잘 나와있어요!

> 인커밍 포트는 도메인 엔티티에 의존성을 가지고 있다. 그 결과, Account 엔티티는 변경할 또 다른 이유가 생겼다.
여기서 Account 엔티티는 인커밍 포트인 SendMoneyUseCase에 의존성이 없는데 인커밍 포트가 어떻게 엔티티를 변경할 수 있는 이유가 될까?
유스케이스가 Account 엔티티 외의 정보를 필요로 할때, Account 엔티티에 새로운 필드를 추가하고 싶다는 생각이 들기 때문이다.


3. 매핑 오버헤드를 이야기한 근본적인 원인은 루시가 이야기해주신 매핑할 필드가 많은 것이고, 메모리나 보일러플레이트에 대한 이야기이지 않을까 싶어요 🤔
